### ISSUE TITLE
Velocity value is unclear

### ISSUE THREAD

**Issue by marler8997** [fabioarnold/zig-gorillas#3]
It's unclear exactly what the valid "velocity" level range is.  The game seems to accept large inputs that don't have much affect on the actual velocity.

**Comment by fabioarnold** [comment]
Maybe print the range like this?
![power](https://user-images.githubusercontent.com/473672/109866675-d4e12c80-7c65-11eb-9a74-8549ac4585d8.png)

**Comment by marler8997** [comment]
perfect
