### ISSUE TITLE
Banana throws seem to take alot of time

### ISSUE THREAD

**Issue by marler8997** [fabioarnold/zig-gorillas#4]
Banana throws are taking between 20 to sometimes 40 seconds.  I played around with the game speed by calling `game.tick()` in a loop.  6x the current speed puts the banana throws between 2 to 7 seconds which seemed to make the game alot more enjoyable to play (for me at least).

**Comment by fabioarnold** [comment]
They take around 20 seconds in the original. I thought it was funny how over the top slow the banana throws were. 😅 So I made them 2x as slow.
I think I'll keep that way for now, sorry. 🤷‍♂️
